# Generated by Django 5.2.3 on 2025-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
